# Generated by Django 2.2.7 on 2019-12-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categorylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=6, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='long',
            field=models.DecimalField(decimal_places=6, default=7, max_digits=9),
            preserve_default=False,
        ),
    ]
