# Generated by Django 2.2.7 on 2019-12-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_list_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='created_at',
        ),
    ]
