# Generated by Django 2.2.7 on 2019-11-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Jina', max_length=20),
            preserve_default=False,
        ),
    ]
